blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogPostListView, BlogPostCreateView, BlogPostDetailView, BlogPostUpdateView, BlogPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog_posts/', BlogPostListView.as_view(), name='blogpost_list'),
    path('blog_create/', BlogPostCreateView.as_view(), name='blogpost_form'),
    path('view/<int:pk>/', BlogPostDetailView.as_view(), name='blogpost_detail'),
    path('edit/<int:pk>/', BlogPostUpdateView.as_view(), name='blogpost_update'),
    path('delete/<int:pk>/', BlogPostDeleteView.as_view(), name='blogpost_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from users.models import NULLABLE


# Create your models here.


class BlogPost(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='media/', verbose_name='Превью', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    views = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Блоговая запись'
        verbose_name_plural = 'Блоговые записи'

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.models import BlogPost


# Create your views here.
class BlogPostListView(LoginRequiredMixin, ListView):
    model = BlogPost


class BlogPostDetailView(LoginRequiredMixin, DetailView):
    model = BlogPost

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)

        cache_key = f'blogpost_{self.object.pk}'
        cache_timeout = 60

        cached_data = cache.get(cache_key)

        if cached_data is None:
            self.object.views += 1
            self.object.save()
            cache.set(cache_key, self.object, cache_timeout)
        else:
            last_updated = timezone.now()
            time_elapsed = timezone.now() - last_updated

            if time_elapsed.total_seconds() >= cache_timeout:
                self.object.views += 1
                self.object.save()
                cache.set(cache_key, self.object, cache_timeout)

        return self.object


class BlogPostCreateView(LoginRequiredMixin, CreateView):
    model = BlogPost
    fields = ('title', 'content', 'preview',)
    success_url = reverse_lazy('blog:blogpost_list')


class BlogPostUpdateView(LoginRequiredMixin, UpdateView):
    model = BlogPost
    fields = ('title', 'content', 'preview',)
    success_url = reverse_lazy('blog:blogpost_list')


class BlogPostDeleteView(DeleteView):
    model = BlogPost
    success_url = reverse_lazy('blog:blogpost_list')

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить пост"{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                    </form>
                </div>
            </div>
        </div>
</div>
{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h5 class="card-title">{{ object.title }}</h5>

                    {% if object.preview %}
                        <img src="{{ object.preview.url }}" width="600" height="600"/>
                    {% endif %}

                    <p class="card-text">{{ object.content }}</p>
                    <p class="card-text">Дата создания: {{ object.created_at }}</p>
                    <p class="card-text">Количество просмотров: {{ object.views }}</p>
                    {% if user.is_staff %}
                        <a href="#" class="btn btn-primary">Редактировать</a>
                        <a href="{% url 'blog:blogpost_delete' object.pk %}" class="btn btn-danger">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blogpost_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">Создать</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'main/base.html' %}

{% block content %}
{% if user.is_staff %}
<a href="{% url 'blog:blogpost_form' %}" class="btn btn-success">Создать пост</a>
{% endif %}
    <div class="row">
        {% for blogpost in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h5 class="card-title">{{ blogpost.title }}</h5>
                        <p class="card-text">{{ blogpost.content }}</p>
                        <a href="{% url 'blog:blogpost_detail' blogpost.pk %}" class="btn btn-primary">Подробнее</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}