blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogPostListView, BlogPostCreateView, BlogPostDetailView, BlogPostUpdateView, BlogPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog_posts/', BlogPostListView.as_view(), name='blogpost_list'),
    path('blog_create/', BlogPostCreateView.as_view(), name='blogpost_form'),
    path('view/<int:pk>/', BlogPostDetailView.as_view(), name='blogpost_detail'),
    path('edit/<int:pk>/', BlogPostUpdateView.as_view(), name='blogpost_update'),
    path('delete/<int:pk>/', BlogPostDeleteView.as_view(), name='blogpost_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users import views
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password, UserListView, DeactivateUserView, verify_email

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('verify/<str:token>/', verify_email, name='verify'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/generate_pass/', generate_new_password, name='generate_new_password'),
    path('user/', UserListView.as_view(), name='user_list'),
    path('deactivate_user/<int:pk>/', DeactivateUserView.as_view(), name='client_deactivate'),
]

users/models.py
import hashlib
import datetime
from datetime import timedelta
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from config.settings import EMAIL_HOST_USER

NULLABLE = {'blank': True, 'null': True}

# Create your models here.


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='адрес')
    avatar = models.ImageField(upload_to='media/', verbose_name='аватар', **NULLABLE)
    activity = models.BooleanField(default=True, verbose_name='статус')
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    verification_key = models.CharField(max_length=255, blank=True, null=True, verbose_name='ключ верификации')


    def send_registration_email(self):
        subject = 'Подтверждение регистрации'
        message = f'Регистрация пользователя {self.email} прошла успешно.'
        from_email = EMAIL_HOST_USER
        confirm_send = [self.email]

        send_mail(subject, message, from_email, confirm_send)

    def save(self, *args, **kwargs):

        is_new_user = not self.pk

        super().save(*args, **kwargs)

        if is_new_user:
            self.send_registration_email()

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from main.models import Mailing, Client, Message
from users.models import User


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ('title', 'start_time', 'end_time', 'message', 'period', 'status', 'clients')

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(MailingForm, self).__init__(*args, **kwargs)

        if user:
            self.fields['message'].queryset = self.fields['message'].queryset.filter(owner=user)
            self.fields['clients'].queryset = self.fields['clients'].queryset.filter(owner=user)

users/views.py
import random
import secrets

from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.core.mail import send_mail
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import CreateView, UpdateView, ListView

from config import settings
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


# Create your views here.
class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        new_user = form.save()
        new_user.verification_key = secrets.randbelow(1_000_000)
        new_user.save()

        token = urlsafe_base64_encode(force_bytes(new_user.verification_key))
        verification_url = reverse('users:verify', kwargs={'token': token})
        send_mail(
            subject='Перейдите по ссылки которая придет к вам на почту.',
            message=f'Для подтвердения регистрации, пройдите по ссылке ниже в письме. \n {self.request.build_absolute_uri(verification_url)}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]
        )
        return super().form_valid(form)

def verify_email(request, token):
    try:
        user_verification_key = urlsafe_base64_decode(token).decode()
        user = User.objects.get(verification_key=user_verification_key)
        if int(user_verification_key) == int(user.verification_key):
            user.is_active = True
            user.save()
            return redirect('users:login')
        else:
            return HttpResponse("Ошибка верификации аккаунта.")
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        return HttpResponse("Ошибка верификации аккаунта.")


class UserListView(ListView):
    model = User

    def get_queryset(self):
        return User.objects.filter(is_superuser=False, is_staff=False)


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

@login_required
def generate_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for i in range(12)])
    send_mail(
        subject='Смена пароля',
        message=f'Новый пароль: {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email],
    )

    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('users:login'))


@login_required
def mailing_list_view(request):
    user = request.user
    is_manager = Group.objects.get(name='Менеджер') in user.groups.all()
    return render(request, 'main.base.html', {'is_manager': is_manager})


class DeactivateUserView(View):
    def get(self, request, pk):
        user = User.objects.get(pk=pk)
        if user.is_active == True:
            user.is_active = False
            user.activity = False
            user.save()
        else:
            user.is_active = True
            user.activity = True
            user.save()

        return redirect('users:user_list')

users/templates/users/login.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
              <div class="card-header">
                <div class="card-body">
                  <h3 class="card-title">
                    Вход
                  </h3>
                    <form method="post">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-success">Войти </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
              <div class="card-header">
                <div class="card-body">
                  <h3 class="card-title">
                    Регистрация
                  </h3>
                    <form class="row" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-success">Регистрация </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
              <div class="card-header">
                <div class="card-body">
                  <h3 class="card-title">
                    Профиль
                  </h3>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-success">Сохранить </button>
                    </form>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать пароль </a>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row">
        {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.email }}</h5>
                        <p class="card-text">Статус - {{ object.is_active }}</p>
                        {% if object.activity %}
                            <a href="{% url 'users:client_deactivate' object.pk %}" class="btn btn-danger">Деактивировать</a>
                        {% else %}
                            <a href="{% url 'users:client_deactivate' object.pk %}" class="btn btn-success">Активировать</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}