blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogPostListView, BlogPostCreateView, BlogPostDetailView, BlogPostUpdateView, BlogPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog_posts/', BlogPostListView.as_view(), name='blogpost_list'),
    path('blog_create/', BlogPostCreateView.as_view(), name='blogpost_form'),
    path('view/<int:pk>/', BlogPostDetailView.as_view(), name='blogpost_detail'),
    path('edit/<int:pk>/', BlogPostUpdateView.as_view(), name='blogpost_update'),
    path('delete/<int:pk>/', BlogPostDeleteView.as_view(), name='blogpost_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import MainConfig
from .views import MessageListView, MessageCreateView, MessageDetailView, MessageUpdateView, MessageDeleteView, \
    ClientListView, ClientCreateView, ClientDetailView, ClientUpdateView, ClientDeleteView, MailingListView, \
    MailingCreateView, MailingUpdateView, MailingDeleteView, MailingDetailView, MainView
from main.services import send_mailing

app_name = MainConfig.name

urlpatterns = [
    path('', cache_page(60)(MainView.as_view()), name='home'),
    path('message_list', MessageListView.as_view(), name='message_list'),
    path('create', MessageCreateView.as_view(), name='message_create'),
    path('view/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('edit/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),

    path('client_view', ClientListView.as_view(), name='client_list'),
    path('client_create', ClientCreateView.as_view(), name='client_create'),
    path('client_detail/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client_edit/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),

    path('mailings_view', MailingListView.as_view(), name='mailing_list'),
    path('mailing_create', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_detail/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing_edit/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('mailing/send/<int:pk>/', send_mailing, name='send')
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users import views
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password, UserListView, DeactivateUserView, verify_email

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('verify/<str:token>/', verify_email, name='verify'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/generate_pass/', generate_new_password, name='generate_new_password'),
    path('user/', UserListView.as_view(), name='user_list'),
    path('deactivate_user/<int:pk>/', DeactivateUserView.as_view(), name='client_deactivate'),
]

main/models.py
from django.db import models
from users.models import User, NULLABLE


class Client(models.Model):
    name = models.CharField(max_length=50, verbose_name='ФИО')
    email = models.EmailField(unique=False, verbose_name='Контактный email')
    commentary = models.TextField(blank=True, verbose_name='Комментарий')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец расслыки', **NULLABLE)

    def __str__(self):
        return f'{self.email}, ({self.name}) - {self.commentary}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    title = models.CharField(max_length=255, verbose_name='Тема письма')
    body = models.TextField(verbose_name='Тело письма')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец расслыки', **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Сообщение для рассылки'
        verbose_name_plural = 'Сообщения для рассылки'


class Mailing(models.Model):
    STATUS_CHOICES = [('создана', 'created'), ('запущена', 'active'), ('завершена', 'completed')]
    PERIOD_CHOICES = [('единожды', 'one_time'), ('ежедневно', 'daily'), ('еженедельно', 'weekly'),
                      ('ежемесячно', 'monthly')]
    start_time = models.DateTimeField(verbose_name='начало рассылки', **NULLABLE)
    end_time = models.DateTimeField(verbose_name='конец рассылки', **NULLABLE)
    title = models.CharField(max_length=150, verbose_name='название рассылки')
    last_sent_date = models.DateTimeField(verbose_name='отправлено в', **NULLABLE)
    period = models.CharField(max_length=15, choices=PERIOD_CHOICES, default='one', verbose_name='периодичность')
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='new', verbose_name='состояние')
    message = models.ForeignKey(Message, on_delete=models.SET_NULL, verbose_name='текст рассылки', **NULLABLE)
    clients = models.ManyToManyField(Client,  verbose_name='клиенты')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец расслыки', **NULLABLE)

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class MailingLog(models.Model):
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE)
    attempt_time = models.DateTimeField(verbose_name='Дата и время попытки')
    attempt_status = models.CharField(max_length=20, verbose_name='Статус попытки')
    server_response = models.TextField(blank=True, verbose_name='Ответ почтового сервера')

    class Meta:
        verbose_name = 'Лог рассылки'
        verbose_name_plural = 'Логи рассылки'

main/views.py
from random import sample

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView, TemplateView

from blog.models import BlogPost
from main.models import Message, Client, Mailing, MailingLog
from users.forms import MailingForm
from users.models import User


class MainView(TemplateView):
    template_name = 'main/include/inc_base.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        unique_clients = User.objects.filter(is_staff=False).count()
        context['unique_clients'] = unique_clients

        all_mailing = Mailing.objects.all().count()
        context['all_mailing'] = all_mailing

        active_mailings = Mailing.objects.filter(status='запущена').count()
        context['active_mailings'] = active_mailings

        all_mailing = Mailing.objects.all().count()
        context['all_mailing'] = all_mailing

        total_mailings = Mailing.objects.count()
        context['total_mailings'] = total_mailings

        if BlogPost.objects.count() >= 3:
            random_blog_posts = sample(list(BlogPost.objects.all()), 3)
        else:
            random_blog_posts = BlogPost.objects.all()
        context['random_blog_posts'] = random_blog_posts
        return context


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_queryset(self):
        queryset = super().get_queryset()

        if not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user)

        return queryset


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    fields = ('title', 'body')
    success_url = reverse_lazy('main:message_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('main:message_list')


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    fields = ('title', 'body')
    success_url = reverse_lazy('main:message_list')


class ClientListView(LoginRequiredMixin, ListView):
    model = Client

    def get_queryset(self):
        queryset = super().get_queryset()

        if not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user)

        return queryset


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    fields = ('name', 'email', 'commentary')
    success_url = reverse_lazy('main:client_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client


class ClientDeleteView(LoginRequiredMixin,DeleteView):
    model = Client
    success_url = reverse_lazy('main:client_list')


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    fields = ('name', 'email', 'commentary')
    success_url = reverse_lazy('main:client_list')


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing

    def get_queryset(self):
        queryset = super().get_queryset()

        if not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user)

        return queryset

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MailingDetailView(DetailView):
    model = Mailing

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user)


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('main:mailing_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class MailingUpdateView(UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('main:mailing_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('main:mailing_list')

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body style="background-color: #343a40">
<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">Блог</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'blog:blogpost_list' %}" class="text-white post-link">Все посты</a></li>
                    </ul>
                </div>
                <div class="col-sm-4 col-md-2 py-4">
                    <h4 class="text-white">Меню рассылок</h4>
                    <ul class="list-unstyled">
                        {% if user.is_staff %}
                            <li><a href="{% url 'main:message_list' %}" class="text-white">Список сообщений</a></li>
                            <li><a href="{% url 'main:mailing_list' %}" class="text-white">Список рассылок</a></li>
                            <li><a href="{% url 'users:user_list' %}" class="text-white">Список пользователей</a></li>
                        {% else %}
                            <li><a href="{% url 'main:message_list' %}" class="text-white">Мои сообщения</a></li>
                            <li><a href="{% url 'main:mailing_list' %}" class="text-white">Мои рассылки</a></li>
                            <li><a href="{% url 'main:client_list' %}" class="text-white">Мои клиенты</a></li>
                        {% endif %}
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'users:profile' %}" class="text-white">Профиль</a></li>
                            <li><a href="{% url 'users:logout' %}" class="text-white">Выйти</a></li>
                        {% else %}
                            <li><a href="{% url 'users:login' %}" class="text-white">Вход</a></li>
                            <li><a href="{% url 'users:register' %}" class="text-white">Зарегистрироваться</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">
    <div class="album py-5 bg-white">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</main>

<footer class="text-muted">
    <div class="container">
        <p>&copy; 2022 - {% now 'Y' %}</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/vendor/holder.min.js' %}"></script>
</body>
</html>

main/templates/main/client_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить клиента "{{ object.name }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                    </form>
                </div>
            </div>
        </div>
</div>
{% endblock %}

main/templates/main/client_detail.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                     <h5 class="card-title">{{ object.name }}</h5>
                     <p class="card-text">{{ object.email }}</p>
                     <a href="{% url 'main:client_list' %}" class="btn btn-success">К списку</a>
                     <a href="{% url 'main:client_update' object.pk %}" class="btn btn-warning">Изменить</a>
                </div>
            </div>
        </div>
</div>
{% endblock %}

main/templates/main/client_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn bnt-primary">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/client_list.html
{% extends 'main/base.html' %}

{% block content %}
{% if user %}
<a href="{% url 'main:client_create' %}" class="btn btn-success">Создать клиента</a>
{% endif %}
    <div class="row">
        {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.name }}</h5>
                        <p class="card-text">{{ object.email }}</p>
                        {% if user %}
                            <a href="{% url 'main:client_detail' object.pk %}" class="btn btn-primary">Детально</a>
                            <a href="{% url 'main:client_delete' object.pk %}" class="btn btn-primary">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

main/templates/main/mailing_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                    </form>
                </div>
            </div>
        </div>
</div>
{% endblock %}

main/templates/main/mailing_detail.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                     <h5 class="card-title">{{ object.title }}</h5>
                        <p class="card-text">{{ object.start_time }} - {{ object.end_time }}</p>
                        <p class="card_footer">{{ object.message}}</p>
                        <p class="card_footer">{{ object.status}}</p>
                        <p class="card_footer">
                            {% for client in object.clients.all %}
                                {{ client.email }}
                            {% endfor %}
                        </p>
                     <a href="{% url 'main:mailing_list' %}" class="btn btn-success">К списку</a>
                     <a href="{% url 'main:mailing_update' object.pk %}" class="btn btn-warning">Изменить</a>
                </div>
            </div>
        </div>
</div>
{% endblock %}

main/templates/main/mailing_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn bnt-primary">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/mailing_list.html
{% extends 'main/base.html' %}

{% block content %}
{% if user %}
<a href="{% url 'main:mailing_create' %}" class="btn btn-success">Создать рассылку</a>
{% endif %}
    <div class="row">
        {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.title }}</h5>
                        <p class="card-text">Старт: {{ object.start_time }}
                        <p class="card-text">Конец: {{ object.end_time }}</p>
                        <p class="card-text">Периодичность: {{ object.period }}</p>
                        <p class="card_footer">Сообщение: {{ object.message}}</p>
                        <p class="card_footer">Статус - {{ object.status}}</p>
                        <p class="card_footer">{{ object.last_sent_date}}</p>
                        <p class="card_footer">Получатели:
                            {% for client in object.clients.all %}
                                {{ client.email }}
                            {% endfor %}
                        </p>
                        <p class="card_footer">Владелец - {{ object.owner}}</p>
                            <a href="{% url 'main:mailing_detail' object.pk %}" class="btn btn-primary">Детально</a>
                        {% if user.user %}
                            <a href="{% url 'main:mailing_delete' object.pk %}" class="btn btn-primary">Удалить</a>
                            <a href="{% url 'main:send' object.pk %}" class="btn btn-primary">Запустить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

main/templates/main/message_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                    </form>
                </div>
            </div>
        </div>
</div>
{% endblock %}

main/templates/main/message_detail.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                     <h5 class="card-title">{{ object.title }}</h5>
                     <p class="card-text">{{ object.body }}</p>
                     <a href="{% url 'main:message_list' %}" class="btn btn-success">На главную</a>
                    {% if user.user %}
                        <a href="{% url 'main:message_update' object.pk %}" class="btn btn-warning">Изменить</a>
                    {% endif %}
                </div>
            </div>
        </div>
</div>
{% endblock %}

main/templates/main/message_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% if form.as_p %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Изменить</button>
                        {% else %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Создать</button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
</div>
{% endblock %}

main/templates/main/message_list.html
{% extends 'main/base.html' %}

{% block content %}
{% if user %}
    <a href="{% url 'main:message_create' %}" class="btn btn-success">Создать сообщение</a>
{% endif %}
    <div class="row">
        {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.title }}</h5>
                        <p class="card-text">{{ object.body }}</p>
                            <a href="{% url 'main:message_detail' object.pk %}" class="btn btn-primary">Детально</a>
                        {% if user.user %}
                            <a href="{% url 'main:message_delete' object.pk %}" class="btn btn-primary">Удалить</a>
                        {% elif user.is_staff %}
                            <p class="card-footer">Создатель - {{ object.owner }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}